version: '3.2'

networks:
  simple_app:
volumes:
  data:
services:

  app:
   image: app:0.1
   deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
   depends_on:
     - app_db
     - web
   networks:
     - simple_app

  db:
   image: app_db:0.1
    deploy:
      replicas: 1
    restart_policy:
      condition: on-failure
    volumes:
      - data:/var/lib/mysql
    networks:
      - simple_app

  web:
  image: app_web:0.1
  depends_on:
     - app
   deploy:
     replicas: 3
   restart_policy:
     condition: on-failure
   ports:
     - 80:80
   networks:
     - simple_app
