INSERT INTO city (id, cname, hotels) VALUES ('1', 'Kiev', 'Ibis');
INSERT INTO city (id, cname, hotels) VALUES ('2', 'Kiev', 'Hilton');
INSERT INTO city (id, cname, hotels) VALUES ('3', 'Kiev', 'Dnipro');
INSERT INTO city (id, cname, hotels) VALUES ('4', 'Kiev', 'Radisson');
INSERT INTO city (id, cname, hotels) VALUES ('5', 'Berlin', 'Radisson');
INSERT INTO city (id, cname, hotels) VALUES ('6', 'Berlin', 'Ibis');
INSERT INTO city (id, cname, hotels) VALUES ('7', 'London', 'Hilton');
INSERT INTO city (id, cname, hotels) VALUES ('8', 'London', 'Ibis');
INSERT INTO city (id, cname, hotels) VALUES ('9', 'London', 'Lanesborough');
